USE [wms]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[t_device](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[wh_id] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[t_device] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[t_device]  WITH CHECK ADD  CONSTRAINT [FK_device_wh] FOREIGN KEY([wh_id])
REFERENCES [dbo].[t_wh] ([id])
GO

ALTER TABLE [dbo].[t_device] CHECK CONSTRAINT [FK_device_wh]
GO
